-- SMARTPARK - Supabase PostgreSQL schema
-- Supabase uses PostgreSQL. The Flask/SQLAlchemy application can also
-- create these tables automatically on first startup.
--
-- Recommended: run this file in Supabase SQL Editor if you want to
-- provision the schema manually before deploying the Flask backend.

create extension if not exists pgcrypto;

drop table if exists sensor_telemetry cascade;
drop table if exists gate_logs cascade;
drop table if exists bookings_and_tickets cascade;
drop table if exists parking_slots cascade;
drop table if exists system_config cascade;
drop table if exists users cascade;

drop type if exists user_role_enum cascade;
drop type if exists slot_type_enum cascade;
drop type if exists slot_status_enum cascade;
drop type if exists sensor_state_enum cascade;
drop type if exists ticket_vehicle_type_enum cascade;
drop type if exists payment_status_enum cascade;
drop type if exists payment_method_enum cascade;
drop type if exists ticket_status_enum cascade;
drop type if exists gate_type_enum cascade;
drop type if exists trigger_source_enum cascade;
drop type if exists action_taken_enum cascade;
drop type if exists sensor_type_enum cascade;

create type user_role_enum as enum ('ADMIN','OPERATOR','CUSTOMER');
create type slot_type_enum as enum ('TWO_WHEELER','COMPACT','SUV','EV');
create type slot_status_enum as enum ('AVAILABLE','RESERVED','OCCUPIED','MAINTENANCE');
create type sensor_state_enum as enum ('EMPTY','DETECTED');
create type ticket_vehicle_type_enum as enum ('TWO_WHEELER','COMPACT','SUV','EV');
create type payment_status_enum as enum ('PENDING','PAID','EXEMPT','FAILED');
create type payment_method_enum as enum ('NONE','CASH','UPI_QR','CREDIT_CARD','FASTAG_SIM');
create type ticket_status_enum as enum ('ACTIVE','COMPLETED','CANCELLED');
create type gate_type_enum as enum ('ENTRY','EXIT');
create type trigger_source_enum as enum ('MANUAL_SIM','ESP32_CAM','IR_SENSOR','API');
create type action_taken_enum as enum ('GATE_OPENED','ACCESS_DENIED','SIMULATED_PASS');
create type sensor_type_enum as enum (
  'IR_ENTRY','IR_ENTRY_PASS','IR_EXIT','IR_EXIT_PASS',
  'SERVO_BARRIER_ENTRY','SERVO_BARRIER_EXIT','SLOT_IR'
);

create table users (
    id integer generated by default as identity primary key,
    username varchar(60) not null unique,
    password_hash varchar(255) not null,
    full_name varchar(100) not null,
    email varchar(120) unique,
    phone varchar(20),
    role user_role_enum not null default 'CUSTOMER',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index idx_users_role on users(role);

create table parking_slots (
    id integer generated by default as identity primary key,
    slot_number varchar(15) not null unique,
    floor_level integer not null default 0,
    zone varchar(10) not null default 'A',
    slot_type slot_type_enum not null default 'COMPACT',
    distance_from_entry integer not null,
    status slot_status_enum not null default 'AVAILABLE',
    sensor_state sensor_state_enum not null default 'EMPTY',
    active_vehicle_number varchar(25),
    last_updated timestamptz default now()
);

create index idx_slot_status_type on parking_slots(status, slot_type);
create index idx_distance on parking_slots(distance_from_entry);

create table bookings_and_tickets (
    id integer generated by default as identity primary key,
    ticket_code varchar(64) not null unique,
    vehicle_number varchar(25) not null,
    vehicle_type ticket_vehicle_type_enum not null default 'COMPACT',
    slot_id integer not null references parking_slots(id) on update cascade on delete restrict,
    user_id integer references users(id) on update cascade on delete set null,
    booking_time timestamptz,
    entry_time timestamptz not null default now(),
    exit_time timestamptz,
    duration_minutes integer default 0,
    base_rate numeric(10,2) not null default 20.00,
    total_amount numeric(10,2) not null default 0.00,
    payment_status payment_status_enum not null default 'PENDING',
    payment_method payment_method_enum not null default 'NONE',
    transaction_id varchar(100),
    status ticket_status_enum not null default 'ACTIVE',
    created_at timestamptz default now()
);

create index idx_vehicle_active on bookings_and_tickets(vehicle_number, status);
create index idx_ticket_code on bookings_and_tickets(ticket_code);

create table gate_logs (
    id integer generated by default as identity primary key,
    gate_type gate_type_enum not null,
    vehicle_number varchar(25),
    anpr_confidence numeric(5,2) default 0.00,
    trigger_source trigger_source_enum not null default 'MANUAL_SIM',
    action_taken action_taken_enum not null default 'GATE_OPENED',
    image_snapshot text,
    notes varchar(255),
    timestamp timestamptz default now()
);

create index idx_gate_timestamp on gate_logs(timestamp);

create table sensor_telemetry (
    id integer generated by default as identity primary key,
    device_id varchar(50) not null,
    sensor_type sensor_type_enum not null,
    state_value varchar(50) not null,
    voltage numeric(4,2) default 3.30,
    recorded_at timestamptz default now()
);

create index idx_device_record on sensor_telemetry(device_id, recorded_at);

create table system_config (
    id integer generated by default as identity primary key,
    config_key varchar(50) not null unique,
    config_value varchar(255) not null,
    description varchar(255),
    updated_at timestamptz default now()
);
